### ISSUE TITLE
Redirect to '/notfound' pushes to browser history resulting in an infinite loop

### ISSUE THREAD

**Issue by finn-vgtl** [svelteuse/router#15]
Navigating to a page which doesn't exist automatically redirects to the path '/notfound' which is the intended behavior. But because v0.1.17 uses the default `.navigate()` function (using `window.pushState()`) to go to '/notfound' it also **updates the history** resulting in something like this:

1. /originalpage
2. /wrongURL
3. /notfound <- you are here

The above history renders the default browser back function useless as returning to the non-existent '/wrongURL' instantly redirects you to '/notfound' again. You'd have to go back two history items to end up on the page you were coming from.

---
### Proposed solution
Using `.window.replaceState()` would replace the URL '/wrongURL' with '/notfound' instead of creating a separate history entry, thus, restoring the browser navigation. Keep in mind though that `.replaceState()` won't refresh the page automatically iirc. But I'd assume you already update everything manually anyway.

**Comment by alexanderniebuhr** [comment]
related to https://github.com/svelteuse/router/issues/16
