### ISSUE TITLE
Add support for skipping history with `$useRouter.navigate()` and `useGuard.goTo()`

### ISSUE THREAD

**Issue by finn-vgtl** [svelteuse/router#16]
https://github.com/svelteuse/router/blob/e6e1d22765277e866e70cbd657a0e0f9c8c87e58/src/index.ts#L180-L184

#### As far as I can tell this should already do the trick:
```DIFF
- navigate: function (path: string) {
+ navigate: function (path: string, history: boolean = true) {
    useRouter.update((storeData) => {
      console.log('navigate to: ' + path)
      if (storeData.mode === 'history') {
-       window.history.pushState(
+       window.history[history ? 'pushState' : 'replaceState'](
          undefined,
          '',
          this.root + path.replace(/\/$/, '').replace(/^\//, '')
        )
      }
```

#### ℹ️ Ping me if you would like to know where exactly we need this functionality

**Comment by alexanderniebuhr** [comment]
[@svelteuse/router@0.2.5](https://github.com/svelteuse/router/compare/e6e1d22765277e866e70cbd657a0e0f9c8c87e58...07c581435975682fc7ebdd2a84667da3e90a26aa)
